[patch."https://github.com/Starry-OS/axdriver.git".axdriver]
branch = "jailhouse_disk"
git = "https://github.com/Josen-B/axdriver.git"

[patch."https://github.com/Starry-OS/axruntime.git".axruntime]
branch = "jailhouse"
git = "https://github.com/Josen-B/axruntime.git"

[patch."https://github.com/Starry-OS/axstarry.git".axstarry]
branch = "jailhouse"
git = "https://github.com/Josen-B/axstarry.git"

[patch."https://github.com/Starry-OS/taskctx.git".taskctx]
branch = "jailhouse"
git = "https://github.com/Josen-B/taskctx.git"

[patch."https://github.com/Starry-OS/linux_syscall_api.git".linux_syscall_api]
git = "https://github.com/Josen-B/linux_syscall_api.git"

[profile.dev]
lto = true

[profile.release]
lto = true

[workspace]
members = ["apps/display", "apps/exception", "apps/helloworld", "apps/memtest", "apps/fs/shell", "apps/net/echoserver", "apps/net/httpclient", "apps/net/httpserver", "apps/net/udpserver", "apps/net/bwbench", "apps/task/parallel", "apps/task/sleep", "apps/task/yield", "apps/task/priority", "apps/task/tls", "apps/monolithic_userboot", "tools/axlibc"]
resolver = "2"
