[patch."https://github.com/Josen-B//axhal.git".axhal]
branch = "phytium-pi"
git = "https://github.com/Josen-B/axhal.git"

[patch."https://github.com/Josen-B//axruntime.git".axruntime]
branch = "phytium-pi"
git = "https://github.com/Josen-B/axruntime.git"

[patch."https://github.com/Josen-B//of.git".of]
branch = "phytium-pi"
git = "https://github.com/Josen-B/of.git"

[profile.dev]
lto = true

[profile.release]
lto = true

[workspace]
members = ["apps/display", "apps/exception", "apps/helloworld", "apps/memtest", "apps/fs/shell", "apps/net/echoserver", "apps/net/httpclient", "apps/net/httpserver", "apps/net/udpserver", "apps/net/bwbench", "apps/task/parallel", "apps/task/sleep", "apps/task/yield", "apps/task/priority", "apps/task/tls", "apps/monolithic_userboot", "tools/axlibc"]
resolver = "2"
